//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fr.epsi.group.multitech.dataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.utilisateurFilmSupport = new HashSet<utilisateurFilmSupport>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string description { get; set; }
        public string realisateur { get; set; }
        public System.DateTime Date_sortie { get; set; }
        public string Pays_origin { get; set; }
        public int id_genre { get; set; }
    
        public virtual GenreFilm GenreFilm { get; set; }
        public virtual ICollection<utilisateurFilmSupport> utilisateurFilmSupport { get; set; }
    }
}
