//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fr.epsi.group.multitech.dataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jeux
    {
        public Jeux()
        {
            this.UtilisateurJeuxSupport = new HashSet<UtilisateurJeuxSupport>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string description { get; set; }
        public System.DateTime Date_sortie { get; set; }
        public string Editeur { get; set; }
        public int id_genre { get; set; }
    
        public virtual GenreJeux GenreJeux { get; set; }
        public virtual ICollection<UtilisateurJeuxSupport> UtilisateurJeuxSupport { get; set; }
    }
}
