//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fr.epsi.group.multitech.dataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supportjeux
    {
        public Supportjeux()
        {
            this.UtilisateurJeuxSupport = new HashSet<UtilisateurJeuxSupport>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<UtilisateurJeuxSupport> UtilisateurJeuxSupport { get; set; }
    }
}
